name: Code Review

on:
  push:
    branches:
      - master  # Trigger only on 'master' branch

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install

      - name: Get Changed Files and Run Review
        run: |
          echo "Getting list of changed files..."
          git fetch --depth=2
          
          # Ensure we're on the correct branch (master)
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $current_branch"
          
          # Set the reference branch to 'origin/master' since we committed to 'master'
          reference_branch="origin/master"
          
          # Get changed files by comparing with 'origin/master'
          changed_files=$(git diff --name-only $reference_branch..HEAD)
          
          if [ -z "$changed_files" ]; then
            echo "No changed files detected."
            exit 0  # Exit if no changes are detected
          fi
          
          echo "Changed files: $changed_files"
          
          # Run review for each changed file
          for file in $changed_files; do
            echo "Reviewing $file..."
            php review_code.php "$file"
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
