name: Code Review

on:
  push:
    branches:
      - master  # Trigger only on 'master' branch

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install

      - name: Get Changed Files and Run Review
        run: |
          echo "Getting list of changed files..."
          
          # Show the last commit for debugging
          echo "Committed files in the last commit:"
          git log -1 --name-only
          
          # Check if there is more than one commit
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            # Compare the last commit with its parent
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          else
            # Fallback for the first commit: list all files
            echo "Only one commit found. Listing all files..."
            changed_files=$(git ls-files)
          fi
          
          if [ -z "$changed_files" ]; then
            echo "No changed files detected."
            exit 0  # Exit if no changes are detected
          fi
          
          echo "Changed files: $changed_files"
          
          # Run review for each changed file
          for file in $changed_files; do
            echo "Reviewing $file..."
            php review_code.php "$file"
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
