name: Code Review

on:
  push:
    branches:
      - master  # or 'main' if you're using that

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install

      - name: Get Changed Files and Run Review
        run: |
          echo "Getting list of changed files..."
          git fetch --depth=2

          # Check if the default branch is 'main' or 'master' and set the reference branch
          reference_branch="origin/main"
          git ls-remote --heads origin master && reference_branch="origin/master"  # Check if 'master' exists

          # Get changed files by comparing with the reference branch
          changed_files=$(git diff --name-only $reference_branch..HEAD)
          
          if [ -z "$changed_files" ]; then
            echo "No changed files detected."
            exit 0  # Exit if no changes are detected
          fi

          echo "Changed files: $changed_files"

          # Run review for each changed file
          for file in $changed_files; do
            echo "Reviewing $file..."
            php review_code.php "$file"
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
