name: Code Review

on:
  push:
    branches:
      - master  # Trigger only on 'master' branch

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install

      - name: Get Changed Files and Run Review
        run: |
          echo "Getting list of changed files..."
          
          # Show the last commit for debugging
          echo "Committed files in the last commit:"
          git log -1 --name-only
          
          # Check if there is more than one commit
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            # Compare the last commit with its parent
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          else
            # Fallback for the first commit: list all files
            echo "Only one commit found. Listing all files..."
            changed_files=$(git ls-files)
          fi
          
          # Avoid redundant output by ensuring only non-empty files are reviewed
          if [ -z "$changed_files" ]; then
            echo "No changed files detected."
            exit 0
          fi
          
          echo "Changed files:"
          echo "$changed_files" | sort | uniq  # Sort and remove duplicates for clean output
          
          # Run review for each unique file
          echo "$changed_files" | sort | uniq | while read -r file; do
            if [ -f "$file" ]; then  # Ensure it's a valid file
              echo "Reviewing $file..."
              php review_code.php "$file" || echo "Error reviewing $file"
            else
              echo "Skipping invalid or deleted file: $file"
            fi
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
