name: Code Review

on:
  push:
    branches:
      - master  # Trigger only on 'master' branch

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install

      - name: Create feedback directory
        run: mkdir -p feedback  # Ensure feedback directory exists

      - name: Get Changed Files and Run Review
        run: |
          echo "Getting list of changed files..."

          # Show the last commit for debugging
          echo "Committed files in the last commit:"
          git log -1 --name-only

          # Check if there is a previous commit (HEAD~1)
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            # Compare the last commit with its parent
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          else
            # If no parent commit, fallback to listing all files in the current commit
            echo "No previous commit found. Listing all files..."
            changed_files=$(git ls-files)
          fi

          # If no changes are detected, exit early
          if [ -z "$changed_files" ]; then
            echo "No changes detected in the latest commit."
            exit 0
          fi

          # Echo the files being reviewed
          echo "Changed files to be reviewed: $changed_files"
          echo "$changed_files" | sort | uniq  # Sort and remove duplicates for clean output

          # Review each changed file and save feedback to respective .txt file
          echo "$changed_files" | sort | uniq | while read -r file; do
            if [ -f "$file" ]; then  # Ensure it's a valid file
              echo "Reviewing $file..."
              feedback_file="feedback/$(basename "$file")_feedback.txt"
              php review_code.php "$file" > "$feedback_file" || echo "Error reviewing $file"
              echo "Feedback for $file saved to $feedback_file"
            else
              echo "Skipping invalid or deleted file: $file"
            fi
          done

      - name: Upload feedback files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: feedback
          path: feedback/

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
